apiVersion: v1
data:
  mapRoles: |
    ---
    - rolearn: arn:aws:iam::069057294951:role/KarpenterNodeRole-car-dev-eksdemo
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::069057294951:role/car-dev-eks-nodegroup-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"---\n- rolearn: arn:aws:iam::069057294951:role/KarpenterNodeRole-car-dev-eksdemo\n  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2025-02-24T22:20:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "895"
  uid: 8b39e93e-ba28-45d9-bc12-7a4451a0b263
